spring:
  application:
    name: zull-service
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# rotas que são direcionadas
zuul:
  prefix: /api
  routes:
    product:
      path: /**/product/*
      serviceId: product-service
    stock:
      path: /**/product/*/stock*
      serviceId: stock-product-service
